apiVersion: v1
kind: Service
metadata:
  name: favorites
  labels:
    app: favorites
spec:
  ports:
  - port: 8383
    name: http
  selector:
    app: favorites
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: favorites-sa
  labels:
    account: favorites
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: favorites
  labels:
    app: favorites
spec:
  replicas: 1
  selector:
    matchLabels:
      app: favorites
  template:
    metadata:
      labels:
        app: favorites
      annotations:
        sidecar.istio.io/userVolume: '[{"name":"wasm-binary","configMap":{"name":"wasm-binary"}}]'
        sidecar.istio.io/userVolumeMount: '[{"mountPath":"/var/local/wasm","name":"wasm-binary"}]'
        sidecar.istio.io/logLevel: "info"
    spec:
      serviceAccountName: favorites-sa
      containers:
      - name: favorites
        image: favorites:0.1.0
        ports:
        - containerPort: 8383
