apiVersion: v1
kind: Service
metadata:
  name: monolith
  labels:
    app: monolith
    service: monolith
spec:
  ports:
  - port: 9292
    name: http
  selector:
    app: monolith
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monolith-sa
  labels:
    account: monolith
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith-v1
  labels:
    app: monolith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monolith
      version: v1
  template:
    metadata:
      labels:
        app: monolith
        version: v1
      annotations:
        sidecar.istio.io/logLevel: "info"
    spec:
      serviceAccountName: monolith-sa
      containers:
      - name: monolith
        image: monolith:0.1.0
        ports:
        - containerPort: 9292
        env:
          - name: RACK_ENV
            value: production
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith-v2
  labels:
    app: monolith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monolith
      version: v2
  template:
    metadata:
      labels:
        app: monolith
        version: v2
      annotations:
        sidecar.istio.io/logLevel: "info"
    spec:
      serviceAccountName: monolith-sa
      containers:
        - name: monolith
          image: monolith:0.1.1
          ports:
            - containerPort: 9292
          env:
            - name: RACK_ENV
              value: production